# Generated by Django 4.1.3 on 2022-11-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата утсановления статуса')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения статуса')),
                ('address', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Имя')),
                ('description', models.CharField(max_length=125)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена товара')),
                ('cover', models.ImageField(upload_to='media/images', verbose_name='Главное фото')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('active', models.BooleanField(default=True, verbose_name='Данный товар активен')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.SmallIntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], verbose_name='Размер')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата нового поступления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='app.order', verbose_name='Заказ')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='app.stock', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app.stock', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='DetailPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Детальное фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='app.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Детальное фото',
                'verbose_name_plural': 'Детальные фото',
            },
        ),
    ]
